
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int CONST = 11;
  public static final int PUNTOYCOMA = 34;
  public static final int TUPLA = 13;
  public static final int LPAREN = 29;
  public static final int INT = 9;
  public static final int FOR = 6;
  public static final int WRITE = 8;
  public static final int RPAREN = 30;
  public static final int NOT = 28;
  public static final int AND = 26;
  public static final int LLLAVE = 31;
  public static final int LT = 24;
  public static final int OR = 27;
  public static final int GET = 17;
  public static final int RLLAVE = 32;
  public static final int ASSIGN = 21;
  public static final int MAIN = 2;
  public static final int IF = 3;
  public static final int EOF = 0;
  public static final int BOOLEAN = 10;
  public static final int RETURN = 12;
  public static final int TRUE = 15;
  public static final int error = 1;
  public static final int MUL = 20;
  public static final int COMA = 33;
  public static final int ADD = 18;
  public static final int NEQ = 23;
  public static final int EQ = 22;
  public static final int ELSE = 4;
  public static final int PUNTO = 35;
  public static final int READ = 7;
  public static final int WHILE = 5;
  public static final int DEF = 14;
  public static final int FALSE = 16;
  public static final int GT = 25;
  public static final int SUB = 19;
  public static final int INT_LITERAL = 37;
  public static final int IDENTIFIER = 36;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "READ",
  "WRITE",
  "INT",
  "BOOLEAN",
  "CONST",
  "RETURN",
  "TUPLA",
  "DEF",
  "TRUE",
  "FALSE",
  "GET",
  "ADD",
  "SUB",
  "MUL",
  "ASSIGN",
  "EQ",
  "NEQ",
  "LT",
  "GT",
  "AND",
  "OR",
  "NOT",
  "LPAREN",
  "RPAREN",
  "LLLAVE",
  "RLLAVE",
  "COMA",
  "PUNTOYCOMA",
  "PUNTO",
  "IDENTIFIER",
  "INT_LITERAL"
  };
}

